### ISSUE TITLE
Benchmarks!

### ISSUE THREAD

**Issue by asubiotto** [asubiotto/distnano#5]
Benchmark runtime for different queries and nanocube construction time. If we implement tree-merge, do that with varying amounts of nodes.

**Comment by fdhoff** [comment]
Datasets:

Gowalla social network - http://snap.stanford.edu/data/loc-gowalla.html
Brightkite social network - http://snap.stanford.edu/data/loc-brightkite.html
Asa flights - http://stat-computing.org/dataexpo/2009/the-data.html

**Comment by fdhoff** [comment]
The ones in his paper cannot be found. Here are some more we might consider, for example the climate dataset:

http://sciencehackday.pbworks.com/w/page/24500475/Datasets

**Comment by asubiotto** [comment]
https://archive.org/details/twitterstream
