### ISSUE TITLE
Fix the time problem

### ISSUE THREAD

**Issue by asubiotto** [asubiotto/distnano#7]
There's a problem with merging time requests because they are specified in relative time so get false answers from servers that only have access to one part of the data. We need to fix this either by putting dummy data signaling the "start" and "end" of time or by manipulating the request or some other way.

**Comment by asubiotto** [comment]
@fdhoff

**Comment by fdhoff** [comment]
Okay, why don't we just talk about it tomorrow when I'm back

**Comment by fdhoff** [comment]
Legends
